#! /bin/sh 
#
# This script is used to fetch and uncompress 
# all beem examples and the run test over all 
# these examples 

# The source adress to check out examples 
DVE_EXAMPLES=http://anna.fi.muni.cz/models/models_data.tar.gz

# The current directory 
SRCDIR=`dirname "$0"`
DATA="$SRCDIR/data"
dc="$SRCDIR/../../iface/dve2/dve2check"

# Download examples i the 
if  ! [ -d "$DATA" ]; then 
    wget $DVE_EXAMPLES 
    tar -xzvf *.tar.gz
fi;


# Now launch all examples 
while read model formula; do 
    path=$(find . -name $model.dve)
    while read line ; do 
	echo "### $dc -e$line -Z $path $formula" 
	$dc -e$line $path "$formula"
    done < algorithms;
done <formulae.txt

# Clean mess 
rm -Rf *.cpp *.dve2C
