#! /bin/sh
# -*- coding: utf-8 -*-
# Copyright (C) 2020 Laboratoire de Recherche et Développement de
# l'Epita (LRDE).
#
# This file is part of Spot, a model checking library.
#
# Spot is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Spot is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo '<?xml version="1.0" encoding="UTF-8"?>'
echo '<testsuites>'
echo '<testsuite name="tests">'
find . -name '*.trs' -print |
while read filename; do
    base=${filename%.trs}
    while read header rest; do
        case $header in
            :global-test-result:) result=$rest;;
            *);;
        esac
    done < $filename
    case $result in
        PASS|XFAIL) tag="system-out";;
        *) tag="error";;
    esac
    tm=`stat -c '%Y-%W' "$base.log" | bc`
    echo -n "<testcase name=\"$base\" time=\"$tm\"><$tag><![CDATA["
    cat "$base.log"
    echo "]]></$tag>"
done
echo '</testsuite>'
echo '</testsuites>'
